#!/usr/bin/env bash

MODULE_CONFIG_DIR="${MODULE_DIR}/config"

MODULE_PACKAGES=(
    # internet
    networkmanager

    # bluetooth
    bluez
    bluez-utils
    blueman

    # audio
    pipewire
    wireplumber
    pipewire-audio
    pipewire-alsa
    pipewire-pulse
    pipewire-jack
    alsa-utils
    pavucontrol
    easyeffects

    # file manager
    thunar
    thunar-archive-plugin
    thunar-volman
    gvfs
    gvfs-mtp
    gvfs-smb
    gvfs-afc
    gvfs-gphoto2
    udiskie
    tumbler
    ffmpegthumbnailer
    file-roller

    # utils
    obsidian
		librewolf
)
MODULE_AUR_PACKAGES=(
)
MODULE_SYSTEM_SERVICES=(
    NetworkManager.service
    bluetooth.service
)
MODULE_USER_SERVICES=(
    pipewire.service
    pipewire-pulse.service
    wireplumber.service
)
