general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
		}

# 5 menit : Redupkan layar ke 10%
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 1%
    on-resume = brightnessctl -r
}

# 30 menit : Kunci layar dan matikan tampilan (DPMS)
listener {
    timeout = 1800
    on-timeout = ~/.config/hypr/scripts/idle-check.sh "hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'"
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
		}

# 1 jam : Suspend sistem
#listener {
#    timeout = 3600
#    on-timeout = ~/.config/hypr/scripts/idle-check.sh "systemctl suspend"
#}



